### PR TITLE
Webkit: implemented launcher tests

### LINKED ISSUE #185: Launch Webkit

### PR DESCRIPTION
**Pull request by Meir017**
closes #185

### CODE REVIEW

**Comment by Meir017** [comment]
@kblok I'm not sure webkit is possible in C#
it doesn't really support websockets, for that they wrap the pipe transport in a WebSocket local server that delegates the actions to the pipe
😢

**Comment by kblok** [comment]
@Meir017 I'll take a look.

**Comment by kblok** [comment]
@Meir017 let's try to ship firefox and chromium first.

**Comment by kblok** [comment]
@Meir017 let's try to ship firefox and chromium first. WebKit is not going to have a v0.10 version.

**Comment by kblok** [comment]
Let's drop this for now.

**Pull request closed without merging**
